const syncRoomData = {
    "code": 0,
    "msg": "ok",
    "data": {
        "now_time": "01:38PM",
        "now_timestamp": 1728893546,
        "display_day": "2024年10月14日星期一",
        "area": {
            "id": "1",
            "disabled": "0",
            "area_name": "BCC-上海办公室",
            "sort_key": "BCC-上海办公室",
            "timezone": "Asia/Shanghai",
            "area_admin_email": "",
            "resolution": "1800",
            "default_duration": "3600",
            "default_duration_all_day": "0",
            "morningstarts": "8",
            "morningstarts_minutes": "0",
            "eveningends": "21",
            "eveningends_minutes": "30",
            "private_enabled": "0",
            "private_default": "0",
            "private_mandatory": "0",
            "private_override": "none",
            "min_create_ahead_enabled": "0",
            "min_create_ahead_secs": "0",
            "max_create_ahead_enabled": "0",
            "max_create_ahead_secs": "604800",
            "min_delete_ahead_enabled": "0",
            "min_delete_ahead_secs": "0",
            "max_delete_ahead_enabled": "0",
            "max_delete_ahead_secs": "604800",
            "max_per_day_enabled": "0",
            "max_per_day": "1",
            "max_per_week_enabled": "0",
            "max_per_week": "5",
            "max_per_month_enabled": "0",
            "max_per_month": "10",
            "max_per_year_enabled": "0",
            "max_per_year": "50",
            "max_per_future_enabled": "0",
            "max_per_future": "100",
            "max_secs_per_day_enabled": "0",
            "max_secs_per_day": "7200",
            "max_secs_per_week_enabled": "0",
            "max_secs_per_week": "36000",
            "max_secs_per_month_enabled": "0",
            "max_secs_per_month": "90000",
            "max_secs_per_year_enabled": "0",
            "max_secs_per_year": "360000",
            "max_secs_per_future_enabled": "0",
            "max_secs_per_future": "360000",
            "max_duration_enabled": "0",
            "max_duration_secs": "7200",
            "max_duration_periods": "2",
            "custom_html": null,
            "approval_enabled": "0",
            "reminders_enabled": "1",
            "enable_periods": "0",
            "periods": "[\"Period 1\",\"Period 2\"]",
            "confirmation_enabled": "1",
            "confirmed_default": "1",
            "times_along_top": "0",
            "default_type": "I",
            "use_exchange": "1",
            "use_wxwork": "0",
            "exchange_server": "mail2013.businessconnectchina.com",
            "wxwork_corpid": "ww09d67060e82cbfa5",
            "wxwork_secret": "4kQjzoLSa1uBR5Ow5UWItaiI7CCSzjFYqzYTgKuR4IA"
        },
        "now_entry": null,
        "entries": [
            {
                "id": 534,
                "start_time": 1728882000,
                "end_time": 1728883800,
                "entry_type": 99,
                "repeat_id": null,
                "room_id": 3,
                "timestamp": "2024-10-14 13:21:51",
                "create_by": "admin",
                "modified_by": "",
                "name": "临时会议",
                "type": "I",
                "description": "临时会议",
                "reminded": null,
                "info_time": null,
                "info_user": null,
                "info_text": null,
                "ical_uid": "MRBS-670caa6f75290-7833041b@172.16.89.91",
                "ical_sequence": 0,
                "ical_recur_id": null,
                "allow_registration": 0,
                "registrant_limit": 1,
                "registrant_limit_enabled": 1,
                "registration_opens": 1209600,
                "registration_opens_enabled": 0,
                "registration_closes": 0,
                "registration_closes_enabled": 0,
                "book_by": "/",
                "exchange_key": "DwAAABYAAAAaFtOjMJukTplygPqsk4HqAAAAAAG2",
                "exchange_id": "AQMkADZmMmRjZDcyLTY1ODctNDc0Yy1hNTUAZC1kMjNiNzg5ZjEyYTEARgAAA278RuINOCJEhaLPCFrOrtwHABoW06Mwm6ROmXKA+qyTgeoAAAIBDQAAABoW06Mwm6ROmXKA+qyTgeoAAAIB1AAAAA==",
                "wxwork_bid": "",
                "create_source": "system",
                "wxwork_sid": "",
                "n_registered": "0",
                "awaiting_approval": false,
                "private": false,
                "tentative": false
            },
            {
                "id": 535,
                "start_time": 1728885600,
                "end_time": 1728892800,
                "entry_type": 0,
                "repeat_id": null,
                "room_id": 3,
                "timestamp": "2024-10-14 13:32:12",
                "create_by": "admin",
                "modified_by": "",
                "name": "research 项目会议's Meeting",
                "type": "I",
                "description": "",
                "reminded": null,
                "info_time": null,
                "info_user": null,
                "info_text": null,
                "ical_uid": "MRBS-670cacdc7f92c-eed42d70@MRBS",
                "ical_sequence": 0,
                "ical_recur_id": null,
                "allow_registration": 0,
                "registrant_limit": 1,
                "registrant_limit_enabled": 1,
                "registration_opens": 1209600,
                "registration_opens_enabled": 0,
                "registration_closes": 0,
                "registration_closes_enabled": 0,
                "book_by": "Jean Fang (BCC)",
                "exchange_key": "DwAAABYAAAAaFtOjMJukTplygPqsk4HqAAAAAAG3",
                "exchange_id": "AQMkADZmMmRjZDcyLTY1ODctNDc0Yy1hNTUAZC1kMjNiNzg5ZjEyYTEARgAAA278RuINOCJEhaLPCFrOrtwHABoW06Mwm6ROmXKA+qyTgeoAAAIBDQAAABoW06Mwm6ROmXKA+qyTgeoAAAIB1QAAAA==",
                "wxwork_bid": "",
                "create_source": "exchange",
                "wxwork_sid": "",
                "n_registered": "0",
                "awaiting_approval": false,
                "private": false,
                "tentative": false
            }
        ],
        "room": {
            "id": "3",
            "disabled": "0",
            "area_id": "1",
            "room_name": "C",
            "sort_key": "C",
            "description": "",
            "capacity": "6",
            "room_admin_email": "synaric.yong@bcc-agi.global",
            "invalid_types": [],
            "custom_html": null,
            "icon": "https://meeting-manage-dev.businessconnectchina.com:11443/image/C.png",
            "exchange_sync_state": "H4sIAAAAAAAEAGNgYGcAAotqE0tHE2NTA0ddZ3NHC10TR2djXSdnJ2ddNyMnC2cnczdLU1OD2vBgveDKvOTgksSSVOfEvMSiSgYr0nW65eekpBZ5pjBYkq43LLWoODM/j8GaaK3+QMuKS4JSk1Mzy1JTQjJzU0nwrU9icYlnXnFJYl5yqncqKb71zS9K9SxJzS32zwtOLSpLLSLByXDfhgNxUW5iUTYklrgYGISA0tDwAxkOUskgCJQyAGI9kJq8P26PeC2UXFoXneeIOrfuDiODlNjlxQazl/jNLGr4tWZy4yuQKkZeBgYmBj4GZhCHmyFyweM/1/bc4WAQYmBk4AVioHXCjAwMvo4Bnr6OfiBFDG6mbmFg5WigGYjlkPgLgdgYizp0gO4sVrC7nDLvOpV8DqprDGqeHDR1btD8xUFLVwWt3RS09WoAhpYgsEGMYGInOQbC9RKvhZ+RoQEAA6BCUDUDAAA=",
            "wxwork_mr_id": "",
            "wxwork_sync_state": "",
            "battery_level": "66"
        }
    }
}

const bookFastMeeting0Data = {
    "code": 0,
    "message": "success",
    "data": {
        "time": "确定要预约 01:30 PM - 02:00 PM的快速会议吗？"
    }
}

export {
	syncRoomData,
	bookFastMeeting0Data
}