const PAD_QUICK_MEETING_TYPE = 99 // 平板端快速会议

const TEMPORARY_MEETING_NONE = 0 // 不开启快速会议
const TEMPORARY_MEETING_LEGACY = 1 // 开启不记名快速会议（旧版）
const TEMPORARY_MEETING_VERIFIED = 2 // 需扫码预约

const MEETING_TO_START = 0 // 待开始
const MEETING_IN_PROGRESS = 1 // 进行中
const MEETING_FINISHED = 2 // 已结束
const MEETING_EXPIRED = 3 // 已过时

export {
	PAD_QUICK_MEETING_TYPE,
	TEMPORARY_MEETING_NONE,
	TEMPORARY_MEETING_LEGACY,
	TEMPORARY_MEETING_VERIFIED,
	MEETING_TO_START,
	MEETING_IN_PROGRESS,
	MEETING_FINISHED,
	MEETING_EXPIRED
}